x-defaults:
  service: &base
    init: true
    restart: always

services:
  backend:
    <<: *base
    image: "10.50.0.7:5001/csam_ai_server/api:2.2.5"
    container_name: server-backend-v2.2.5
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - ./data:/api/data
      - ./config:/api/config
    networks:
      - load_balancer

  frontend:
    <<: *base
    image: "10.50.0.7:5001/csam_ai_server/app:2.2.5"
    container_name: server-frontend-v2.2.5
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - load_balancer

networks:
  load_balancer:
    driver: bridge



    
